MODEL:
  NAME: "unet_default"
  SKIP_PROCESS: "NULL" # NULL, ONE_RES, DUAL_RES
DATA:
  NAME: "ISIC2016"
  BATCH_SIZE: 1
  IMAGE_SIZE: [64, 64]
  WORLD_SIZE: 1
  NUM_WORKERS: 0
OPTIM:
  NAME: "adam"
  BASE_LR: 8e-4
  WARMUP_LR: 8e-4
  WEIGHT_DECAY: 1e-4
  DROPOUT: 0.1
TRAIN:
  EPOCHS: 2
SEED: 3407


SP:
  NUM_GROUPS: 1